trainer:
  name: Trainer
  num_epochs: 50
  output_dir: experiments/catsdogs

model:
  name: efficientnet_b0
  num_classes: 2

dataset:
  name: ImageNetDataLoader
  root: "C:/Users/akhro/OneDrive/Рабочий стол/MachineLearning/mlsem1/kagglecatsanddogs_5340/PetImages"
  batch_size: 16
  image_size: 224
  num_workers: 8

optimizer:
  name: TFRMSprop
  lr: 0.0125
  weight_decay: 0
  rho: 0.9
  eps: 1.e-3
  momentum: 0.9
  warmup: 1000

scheduler:
  name: ExponentialLR
  gamma: 0.98738885893
