trainer:
  name: Trainer
  num_epochs: 50
  output_dir: experiments/TASK

model:
  name: efficientnet_b0
  num_classes: 6

dataset:
  name: ImageNetDataLoader
  root: "C:/Users/akhro/OneDrive/Рабочий стол/mvers/Images/DataSet"
  batch_size: 32
  image_size: 224
  num_workers: 16

optimizer:
  name: TFRMSprop
  lr: 0.0125
  weight_decay: 0
  rho: 0.9
  eps: 1.e-3
  momentum: 0.9
  warmup: 200185

scheduler:
  name: ExponentialLR
  gamma: 0.98738885893
